### ISSUE TITLE
Add unit test framework to coppercore

### ISSUE THREAD

**Issue by jkleiber** [team401/coppercore#10]
The objective of this ticket is to add a unit testing framework to the library, while also providing an example of how it works.

This can be anything as long as it is easy to use and understand by other members of the team. The way to gain buy in is:
- develop an example that uses the framework
- document how to use it (should be automatically run as part of gradle builds imo)
- integrate it into CI testing

**Comment by avidraccoon** [comment]
It appears there is a system in gradle for unit testing. Should I just make an example of using that so other people can see how to implement gradle's system?

**Comment by jkleiber** [comment]
@avidraccoon yeah let's do that to start

**Comment by avidraccoon** [comment]
Should I show examples of how to set it up to be able to isolate certain parts to be tested?

Also, could you let me know what examples you want me to make?

**Comment by jkleiber** [comment]
@avidraccoon I recommend adding a feature to coppercore and then making a unit test for it. That can serve as the example. 

If you can easily write multiple test cases with good coverage that would be best, but a single test to show normal operations work would be fine as well

**Comment by avidraccoon** [comment]
@jkleiber Do you still want me to do this, because I think just using J Unit works fine.

**Comment by jkleiber** [comment]
JUnit satisfies our needs, so this ticket doesn't need to be worked
