### ISSUE TITLE
Publish copperore to mavenCentral

### ISSUE THREAD

**Issue by linglejack06** [team401/coppercore#11]

**Comment by linglejack06** [comment]
@jkleiber could you go in and update the new repository I created in team401 to public. Part of the setup to publish on mavenCentral is verifying the github url.

**Comment by linglejack06** [comment]
the repository is called jskdiiwjn7

**Comment by jkleiber** [comment]
done @linglejack06

**Comment by linglejack06** [comment]
thank you, maven central is hopeflly going to verify it soon, then I can delete the repository. This should allow us to host the coppercore through maven with an org name of io.github.team401 (which allows us to not need a domain name)

**Comment by aidnem** [comment]
We used Jitpack instead; this is now unnecessary
