### ISSUE TITLE
Figure Out Why We Can't Use Some WPILib Features

### ISSUE THREAD

**Issue by aidnem** [team401/coppercore#27]
**Purpose**
When trying to extend Subsystem or Command, the build fails and the following compile error is thrown:
```
/__w/coppercore/coppercore/wpi_interface/src/main/java/feedforward_tuning/TuneS.java:9: error: cannot access Sendable
```
This can be observed on for dev branches for #26 and #24 (both of them are failing build checks). Neither of them use Sendable directly, so we can reasonably assume it's something under the hood that gets imported by WPILib that then can't be found. This could be due to having an incompatible version of WPILib or incorrectly installing the library.
**Scope**
- [x]  Figure out why we can't use Subsystem or Command
- [x] Fix whatever needs to be fixed (probably in build.gradle)

**Comment by aidnem** [comment]
@jkleiber Would you mind taking this one? I've wrestled with it for a few days and I'm not really getting anywhere.

**Comment by jkleiber** [comment]
I'll look into it @aidnem

**Comment by aidnem** [comment]
Thanks!

**Comment by aidnem** [comment]
Figured it out:
Whenever a package can't be found, check the [wpilib package repository under frcmaven](https://frcmaven.wpi.edu/ui/native/release/) for the package and add it to your build.gradle.
Example: I couldn't use SubsystemBase because it said Sendable couldn't be found, but by adding the following to my build.gradle it was fixed:
```java
	implementation 'edu.wpi.first.wpiutil:wpiutil-java:2024.3.2'
```
