### ISSUE TITLE
Basic Vision Subsystem

### ISSUE THREAD

**Issue by aidnem** [team401/coppercore#30]
Add a simple vision subsystem that takes configurable cameras, creates a photon pose estimator, and can send vision measurements according to the [PhotonLib reference docs](https://docs.photonvision.org/en/latest/docs/programming/photonlib/index.html).
This is intended to be the most basic element of the vision system, and doesn't need to implement any advanced features yet.

**Scope**
- [x] Add a VisionLocalizer class to WPI interface.
- [x] Allow it to have cameras passed in to its constructor (must be capable of being used in any robot project without changing its code)
- [x] Allow setting of a callback to add a vision measurement when a new one is available.
- [ ] Simulate it
Verification criteria:
- [ ] Vision system in coppercore
- [ ] Vision works in sim w/ the following:
- [ ] Robot detects tags
- [ ] Estimated pose is reasonably close to odometry (compare vision ghost to drivetrain sim position)

**Comment by aidnem** [comment]
@jkleiber for now I'm putting vision subsystem under WPI interface as it depends on WPILib. Do you think it would be better suited to its own package?

**Comment by jkleiber** [comment]
@aidnem I think it's better as it's own package. Maybe we just have to accept having WPILib in more than one package

**Comment by aidnem** [comment]
@jkleiber we could also put it under coppercore.wpilib_interface.vision

**Comment by jkleiber** [comment]
I'm actually fine with it being in a separate package because small dedicated and specific packages > big multifunctional packages. If we decide to move it into the WPILib interface later that's easier than extracting it imo

**Comment by jkleiber** [comment]
Incremental build up >>>

**Comment by aidnem** [comment]
That's what I figured you'd say

**Comment by aidnem** [comment]
I'm going to make this able to be simulated before I merge it since sim is a priority

**Comment by aidnem** [comment]
@jkleiber do you want this to use 2024 or 2025 photon vision? I'm leaning toward 2025 because I haven't found any issues with it interfacing with wpilib 2024 and I would like to have it be as similar as possible to next year's competition season vision code. If you have any reason not to use this I'll gladly switch back to 2024.

**Comment by jkleiber** [comment]
Let's do 2025 so we can get as much mileage on that as possible 

That being said, as much of the code as possible should be PhotonVision version-agnostic (mainly thinking of pose rejection, which can be generalized to some extent)

**Comment by aidnem** [comment]
Yes, the main feature of 2025 I want to use is that it returns a list of unread results instead of only the latest result, which means we can guarantee not processing duplicate measurements and also guarantee that no measurements are missed (unless we have a huge loop overrun that causes the measurement buffer to be overwritten with new measurements).
