### ISSUE TITLE
Replace wpi_interface with wpilib_interface

### ISSUE THREAD

**Issue by aidnem** [team401/coppercore#32]
The file structure contains a folder: wpi_interface, but the java source files themselves describe themselves as being part of package coppercore.wpilib_interface.

Use wpilib_interface for everything, all tickets on wpi_interface should rename it to wpilib_interface before they are merged!

**Comment by aidnem** [comment]
@linglejack06 @avidraccoon please be sure to rename wpi_interface to wpilib_interface in the files and in the settings.gradle before merging your PRs.

**Comment by jkleiber** [comment]
done in #36
