### ISSUE TITLE
Utilize Maven Central

### ISSUE THREAD

**Issue by linglejack06** [team401/coppercore#39]
Summary: Jitpack is very slow and unreliable, the hope is that by switching to maven central we can have a more reliable library import

- add maven central publishing
- possibly add to ci so its automated?

**Comment by jkleiber** [comment]
Done in #57

**Comment by linglejack06** [comment]
@jkleiber is coppercore still imported the same way into our robot code?

**Comment by jkleiber** [comment]
@linglejack06 see the high-key PR about coppercore for how to use it now

**Comment by linglejack06** [comment]
i figured it out based off of readme, i didn't look for that at first
