### ISSUE TITLE
Add saving json

### ISSUE THREAD

**Issue by avidraccoon** [team401/coppercore#45]
- [x] Add Functionality
- [x] Check Functionality
- [ ] Write Tests

**Comment by avidraccoon** [comment]
@jkleiber how does this look im about to write the tests for it.

**Comment by jkleiber** [comment]
@avidraccoon it looks good from a high level. It would be cool if the json pretty-printed to the file, but not required right now if that's difficult

**Comment by avidraccoon** [comment]
It does currently save to a file 
```json
{
    "testText": "Hello World",
    "testDouble": 10.0,
    "testInt": 2,
    "motorData": {
        "minVoltage": -12.3,
        "maxVoltage": 16.4,
        "currentVoltage": 0.0
    }
}
```

**Comment by avidraccoon** [comment]
Nevermind I was looking at the wrong file I think I can quickly implement that though @jkleiber

**Comment by avidraccoon** [comment]
Ok the commit I just made should have added it
