### ISSUE TITLE
Migrate CopperCore to submodule

### ISSUE THREAD

**Issue by aidnem** [team401/coppercore#5]
**Purpose**
Migrate this library to be used as a submodule rather than as a vendor dep.

**Scope**
- [ ] Figure out how to use a library effectively as a submodule
- [ ] Re-structure this repository to be used as a submodule

**Comment by aidnem** [comment]
@linglejack06 I can figure out how to do this if you want me to, otherwise you can handle it. I'm good either way.

**Comment by minhnguyenbhs** [comment]
@aidnem how did you figure out how to do this yesterday? sorry- thank you!

**Comment by minhnguyenbhs** [comment]
SORRY i'm thoughtvomiting figured it out

**Comment by jkleiber** [comment]
this is unnecessary now that #9 is complete via #8
