### ISSUE TITLE
Enable publishing of modules

### ISSUE THREAD

**Issue by aidnem** [team401/coppercore#9]
**Purpose**
Enable publishing of modules so that gradle builds artifacts so that the library can be used from 2024-Robot-Code.

**Scope**
Update gradle build scripts as described in the [jitpack building docs](https://jitpack.io/docs/BUILDING/). Refer to the [jitpack example multi-module repo](https://github.com/jitpack/gradle-modular) for examples.

**Comment by jkleiber** [comment]
Done incidentally in #12
